repos:
  - repo: local
    hooks:
      - id: dev
        name: develop release
        entry: .venv/bin/maturin develop --release
        language: system
        pass_filenames: false

      - id: pytest
        name: Run pytest
        entry: .venv/bin/pytest tests/test.py
        language: system
        pass_filenames: false

      - id: clippy
        name: Run clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
