[package]
name = "oxapy"
version = "0.11.1"
edition = "2024"
authors = ["FITAHIANA Nomeniavo Joe <24nomeniavo@gmail.com>"]
repository = "https://github.com/j03-dev/oxapy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oxapy"
crate-type = ["cdylib", "rlib"]

[features]
default = []
stub_gen = ["pyo3-stub-gen/infer_signature"]


[dependencies]
# Python bindings
pyo3 = ">=0.29.0"
pyo3-async-runtimes = { version = "0.29.0", features = ["tokio-runtime"] }
pyo3-stub-gen = { git = "https://github.com/Jij-Inc/pyo3-stub-gen", branch = "main", default-features = false, features = [
  "either",
  "numpy",
  "ordered-float",
] }

# Async / Futures
futures-util = "0.3.33"
tokio = { version = "1", features = ["full"] }

# HTTP stack
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
multer = "3.1.0"

# Routing
matchit = { git = "https://github.com/ibraheemdev/matchit", branch = "master" }

# Serialization / Data formats
serde = "1.0.229"
serde_json = "1.0.151"
jsonschema = { version = "0.49.6", default-features = false }

# Template engines
tera = { version = "2", features = ["glob_fs"] }

# Utilities
ahash = "0.8.12"
ctrlc = "3.5.2"
glob = "0.3.4"
rand = "0.10.2"
url = "2.5.8"

jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
