class BaseError(BaseException): ...
class NotFoundError(BaseError): ...
class UnauthorizedError(BaseError): ...
class BadRequestError(BaseError): ...
class InternalError(BaseError): ...
class ValidationException(BaseError): ...
