# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
import typing_extensions
__all__ = [
    "Template",
]

@typing.final
class Template:
    r"""
    Template engine for rendering HTML templates using Tera.
    
    Templates are loaded lazily via `load()`. Custom functions must be registered
    with `register_function()` before calling `load()`.
    
    Args:
        None
    
    Returns:
        Template: A new empty template engine instance.
    
    Example:
    ```python
    from oxapy import templating
    
    template = templating.Template()
    template.register_function("_t", translate)
    template.load("./templates/**/*.html")
    result = template.render("index.html", {"title": "Hello"})
    ```
    """
    def __new__(cls) -> typing_extensions.Self:
        r"""
        Create a new empty Template instance.
        
        Templates are not loaded at construction time. Use `register_function()` to add
        custom functions, then `load()` to load and validate templates.
        
        Args:
            None
        
        Returns:
            Template: A new empty template engine instance.
        
        Example:
        ```python
        from oxapy import templating
        
        template = templating.Template()
        template.register_function("_t", translate)
        template.load("./templates/**/*.html")
        ```
        """
    def load(self, dir: builtins.str = './templates/**/*.html') -> None:
        r"""
        Load templates from a directory glob pattern.
        
        This parses and validates all matching template files. Any custom functions
        registered with `register_function()` must be added **before** calling `load()`,
        otherwise Tera will raise an error for unknown functions.
        
        Args:
            dir (str, optional): Glob pattern to search for templates (default: "./templates/**/*.html").
        
        Returns:
            None
        
        Raises:
            RuntimeError: If the template engine is shared across multiple references.
            PyException: If the glob pattern is invalid or templates contain errors.
        
        Example:
        ```python
        from oxapy import templating
        
        template = templating.Template()
        template.register_function("_t", translate)
        template.load("./templates/**/*.html")
        ```
        """
    def register_function(self, name: builtins.str, callable: typing.Any) -> None:
        r"""
        Register a Python function as a custom template function.
        
        This method allows you to expose Python callables to be used within Tera templates.
        The function will receive keyword arguments from the template call and should return
        a value that can be serialized to JSON.
        
        **Important:** All functions must be registered **before** calling `load()`.
        Tera validates function existence at template load time.
        
        Args:
            name (str): The name used to call the function from templates (e.g., `{{ my_function(key=value) }}`).
            callable (Callable): A Python callable that accepts keyword arguments and returns a value.
        
        Returns:
            None
        
        Raises:
            RuntimeError: If called after `load()` has been invoked.
        
        Example:
        ```python
        template = templating.Template()
        template.register_function("add", lambda a, b: a + b)
        template.load("./templates/**/*.html")
        # In template: {{ add(a=1, b=2) }} -> 3
        ```
        """

